#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author: Kong Xiaoshuang
Date: 7/20/26
Description: enums
"""

from enum import Enum


class StringEnum(str, Enum):
    """
    Compatible string enum for Python 3.10+.

    Enum members can be serialized directly as strings in JSON/Pydantic.
    """

    def __str__(self) -> str:
        return self.value


class TaskMode(StringEnum):
    """The task being performed on the input text."""

    INCLUSIVE_REWRITING = "INCLUSIVE_REWRITING"
    SOURCE_FAITHFUL_SUMMARIZATION = "SOURCE_FAITHFUL_SUMMARIZATION"
    TRANSLATION = "TRANSLATION"
    ANONYMIZATION = "ANONYMIZATION"
    BIAS_EXPLANATION = "BIAS_EXPLANATION"
    ARCHIVAL_PRESERVATION = "ARCHIVAL_PRESERVATION"


class GenderCueType(StringEnum):
    """Surface or inferred type of a gender-related cue."""

    PRONOUN = "PRONOUN"
    KINSHIP_TERM = "KINSHIP_TERM"
    TITLE_ADDRESS = "TITLE_ADDRESS"
    GENDERED_PERSON_NOUN = "GENDERED_PERSON_NOUN"
    OCCUPATION_MARKER = "OCCUPATION_MARKER"
    IDENTITY_TERM = "IDENTITY_TERM"
    BIOLOGICAL_TERM = "BIOLOGICAL_TERM"
    REPRODUCTIVE_ROLE = "REPRODUCTIVE_ROLE"
    GENDERED_EVALUATION = "GENDERED_EVALUATION"
    GENERIC_GENDER_FORM = "GENERIC_GENDER_FORM"
    ORTHOGRAPHIC_MARKER = "ORTHOGRAPHIC_MARKER"

    STEREOTYPICAL_ATTRIBUTE = "STEREOTYPICAL_ATTRIBUTE"
    ROLE_ASSOCIATION = "ROLE_ASSOCIATION"
    GENDERED_PRESUPPOSITION = "GENDERED_PRESUPPOSITION"
    DEFAULT_GENDER_INFERENCE = "DEFAULT_GENDER_INFERENCE"
    COREFERENCE_INFERENCE = "COREFERENCE_INFERENCE"
    PRAGMATIC_IMPLICATION = "PRAGMATIC_IMPLICATION"

    NO_GENDER_CUE = "NO_GENDER_CUE"
    OTHER = "OTHER"


class Explicitness(StringEnum):
    """Whether a gender cue is directly expressed in the text."""

    EXPLICIT = "EXPLICIT"
    IMPLICIT = "IMPLICIT"
    NONE = "NONE"
    UNDETERMINED = "UNDETERMINED"


class GenderDimension(StringEnum):
    """
    The semantic dimension represented by the gender information.

    Sex characteristics, gender identity, grammatical gender and perceived
    gender must not be collapsed into a single label.
    """

    SEX_CHARACTERISTIC = "SEX_CHARACTERISTIC"
    GENDER_IDENTITY = "GENDER_IDENTITY"
    GENDER_EXPRESSION = "GENDER_EXPRESSION"
    SOCIAL_GENDER_ROLE = "SOCIAL_GENDER_ROLE"
    GRAMMATICAL_GENDER = "GRAMMATICAL_GENDER"
    GENDER_REFERENCE = "GENDER_REFERENCE"
    PERCEIVED_GENDER = "PERCEIVED_GENDER"
    UNKNOWN_DIMENSION = "UNKNOWN_DIMENSION"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class GenderValue(StringEnum):
    """Gender value explicitly stated or grounded in context."""

    FEMALE = "FEMALE"
    MALE = "MALE"
    NON_BINARY = "NON_BINARY"
    MIXED_GROUP = "MIXED_GROUP"
    MULTIPLE_GENDERS = "MULTIPLE_GENDERS"
    UNKNOWN = "UNKNOWN"
    UNSPECIFIED = "UNSPECIFIED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ReferentType(StringEnum):
    """The kind of entity to which a gender cue refers."""

    SPECIFIC_PERSON = "SPECIFIC_PERSON"
    SPECIFIC_GROUP = "SPECIFIC_GROUP"
    GENERIC_PERSON = "GENERIC_PERSON"
    GENERIC_GROUP = "GENERIC_GROUP"
    HYPOTHETICAL_PERSON = "HYPOTHETICAL_PERSON"
    FICTIONAL_PERSON = "FICTIONAL_PERSON"
    HISTORICAL_PERSON = "HISTORICAL_PERSON"
    UNKNOWN_REFERENT = "UNKNOWN_REFERENT"
    NO_REFERENT = "NO_REFERENT"


class GenderSource(StringEnum):
    """Where the gender information comes from."""

    SELF_IDENTIFIED = "SELF_IDENTIFIED"
    EXPLICITLY_STATED = "EXPLICITLY_STATED"
    DOCUMENTED_RECORD = "DOCUMENTED_RECORD"
    AUTHOR_ASSIGNED = "AUTHOR_ASSIGNED"
    QUOTED_SOURCE = "QUOTED_SOURCE"
    CONTEXTUALLY_INFERRED = "CONTEXTUALLY_INFERRED"
    STEREOTYPE_INFERRED = "STEREOTYPE_INFERRED"
    MODEL_INFERRED = "MODEL_INFERRED"
    UNKNOWN = "UNKNOWN"


class SourceReliability(StringEnum):
    """Reliability of the gender-information source."""

    CONFIRMED = "CONFIRMED"
    SUPPORTED = "SUPPORTED"
    INFERRED = "INFERRED"
    SPECULATIVE = "SPECULATIVE"
    CONTRADICTORY = "CONTRADICTORY"
    UNKNOWN = "UNKNOWN"


class FunctionLabel(StringEnum):
    """
    Semantic and pragmatic functions performed by gender information.

    A mention may have multiple function labels.
    """

    # Reference and identity
    IDENTIFICATION = "IDENTIFICATION"
    DISAMBIGUATION = "DISAMBIGUATION"
    COREFERENCE = "COREFERENCE"
    KINSHIP_RELATION = "KINSHIP_RELATION"
    PERSONAL_IDENTITY = "PERSONAL_IDENTITY"

    # Domain facts
    BIOLOGICAL_MEDICAL = "BIOLOGICAL_MEDICAL"
    REPRODUCTIVE = "REPRODUCTIVE"
    LEGAL_ADMINISTRATIVE = "LEGAL_ADMINISTRATIVE"
    DEMOGRAPHIC_STATISTICAL = "DEMOGRAPHIC_STATISTICAL"
    ELIGIBILITY_OR_ACCESS = "ELIGIBILITY_OR_ACCESS"

    # Discourse functions
    TOPIC_CONTINUITY = "TOPIC_CONTINUITY"
    CONTRASTIVE = "CONTRASTIVE"
    COMPARATIVE = "COMPARATIVE"
    EXPLANATORY = "EXPLANATORY"
    CAUSAL = "CAUSAL"
    CATEGORY_CONSTRUCTION = "CATEGORY_CONSTRUCTION"

    # Social and historical functions
    HISTORICAL_SIGNIFICANCE = "HISTORICAL_SIGNIFICANCE"
    REPRESENTATIONAL_VISIBILITY = "REPRESENTATIONAL_VISIBILITY"
    UNDERREPRESENTED_IDENTITY = "UNDERREPRESENTED_IDENTITY"
    AFFIRMATIVE_RECOGNITION = "AFFIRMATIVE_RECOGNITION"
    SOCIAL_INEQUALITY_DESCRIPTION = "SOCIAL_INEQUALITY_DESCRIPTION"

    # Quotation and metalinguistic functions
    DIRECT_QUOTATION = "DIRECT_QUOTATION"
    REPORTED_SPEECH = "REPORTED_SPEECH"
    METALINGUISTIC_MENTION = "METALINGUISTIC_MENTION"
    BIAS_CRITIQUE = "BIAS_CRITIQUE"
    EDUCATIONAL_EXAMPLE = "EDUCATIONAL_EXAMPLE"

    # Narrative and stylistic functions
    NARRATIVE_CHARACTERIZATION = "NARRATIVE_CHARACTERIZATION"
    PERSONA_CONSTRUCTION = "PERSONA_CONSTRUCTION"
    RHETORICAL_EFFECT = "RHETORICAL_EFFECT"
    IRONY_OR_SATIRE = "IRONY_OR_SATIRE"
    VOICE_PRESERVATION = "VOICE_PRESERVATION"

    # Generic or potentially unnecessary functions
    GENERIC_REFERENCE = "GENERIC_REFERENCE"
    GROUP_GENERALIZATION = "GROUP_GENERALIZATION"
    INCIDENTAL_DESCRIPTION = "INCIDENTAL_DESCRIPTION"
    UNNECESSARY_MARKING = "UNNECESSARY_MARKING"

    UNKNOWN_FUNCTION = "UNKNOWN_FUNCTION"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class Necessity(StringEnum):
    """How necessary the gender information is in the current context."""

    ESSENTIAL = "ESSENTIAL"
    RELEVANT = "RELEVANT"
    OPTIONAL = "OPTIONAL"
    INCIDENTAL = "INCIDENTAL"
    HARMFUL_OR_MISLEADING = "HARMFUL_OR_MISLEADING"
    UNDETERMINED = "UNDETERMINED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class NecessityReason(StringEnum):
    """Why gender information should be preserved, changed or removed."""

    TRUTH_CONDITIONAL = "TRUTH_CONDITIONAL"
    REFERENT_IDENTIFICATION = "REFERENT_IDENTIFICATION"
    COREFERENCE_RESOLUTION = "COREFERENCE_RESOLUTION"
    KINSHIP_RELATION = "KINSHIP_RELATION"
    DOMAIN_REQUIREMENT = "DOMAIN_REQUIREMENT"
    TASK_REQUIREMENT = "TASK_REQUIREMENT"
    IDENTITY_RESPECT = "IDENTITY_RESPECT"
    HISTORICAL_SIGNIFICANCE = "HISTORICAL_SIGNIFICANCE"
    REPRESENTATIONAL_RELEVANCE = "REPRESENTATIONAL_RELEVANCE"
    DISCOURSE_COHERENCE = "DISCOURSE_COHERENCE"
    QUOTATION_FIDELITY = "QUOTATION_FIDELITY"
    SPEAKER_VOICE = "SPEAKER_VOICE"
    PRIVACY_PROTECTION = "PRIVACY_PROTECTION"
    NO_COMMUNICATIVE_RELEVANCE = "NO_COMMUNICATIVE_RELEVANCE"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


class BiasStatus(StringEnum):
    """Whether the mention or proposition expresses gender bias."""

    NONE = "NONE"
    POTENTIAL = "POTENTIAL"
    IMPLICIT = "IMPLICIT"
    EXPLICIT = "EXPLICIT"
    CONTESTED = "CONTESTED"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


class BiasMechanism(StringEnum):
    """Mechanism through which gender bias is expressed."""

    GENERIC_MALE_DEFAULT = "GENERIC_MALE_DEFAULT"
    UNNECESSARY_GENDER_MARKING = "UNNECESSARY_GENDER_MARKING"
    STEREOTYPE_ASSOCIATION = "STEREOTYPE_ASSOCIATION"
    ESSENTIALIST_GENERALIZATION = "ESSENTIALIST_GENERALIZATION"
    PRESCRIPTIVE_ROLE_NORM = "PRESCRIPTIVE_ROLE_NORM"
    COMPETENCE_OR_AGENCY_DENIAL = "COMPETENCE_OR_AGENCY_DENIAL"
    ASYMMETRY_OR_DOUBLE_STANDARD = "ASYMMETRY_OR_DOUBLE_STANDARD"
    OBJECTIFICATION = "OBJECTIFICATION"
    SEXUALIZATION = "SEXUALIZATION"
    DEROGATION_OR_SLUR = "DEROGATION_OR_SLUR"
    PATERNALISM = "PATERNALISM"
    BENEVOLENT_SEXISM = "BENEVOLENT_SEXISM"
    POSITIVE_STEREOTYPE = "POSITIVE_STEREOTYPE"
    IDENTITY_INVALIDATION = "IDENTITY_INVALIDATION"
    MISGENDERING = "MISGENDERING"
    EXCLUSION = "EXCLUSION"
    ERASURE = "ERASURE"
    STATISTICAL_OVERGENERALIZATION = "STATISTICAL_OVERGENERALIZATION"
    UNSUPPORTED_GENDER_INFERENCE = "UNSUPPORTED_GENDER_INFERENCE"
    INTERSECTIONAL_BIAS = "INTERSECTIONAL_BIAS"


class SpeakerStance(StringEnum):
    """The speaker or author's stance toward a biased proposition."""

    ENDORSE = "ENDORSE"
    REPORT = "REPORT"
    QUOTE = "QUOTE"
    REJECT = "REJECT"
    QUESTION = "QUESTION"
    SATIRIZE = "SATIRIZE"
    DISTANCE = "DISTANCE"
    NEUTRAL_REPORT = "NEUTRAL_REPORT"
    UNCLEAR = "UNCLEAR"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class Action(StringEnum):
    """Fine-grained action applied to a mention or proposition span."""

    KEEP = "KEEP"
    KEEP_WITH_ATTRIBUTION = "KEEP_WITH_ATTRIBUTION"

    NEUTRALIZE = "NEUTRALIZE"
    UNMARK = "UNMARK"
    GENERALIZE = "GENERALIZE"
    SPECIFY_OR_RESTORE = "SPECIFY_OR_RESTORE"

    CORRECT_IDENTITY = "CORRECT_IDENTITY"
    REPLACE_GENERIC_FORM = "REPLACE_GENERIC_FORM"
    STANDARDIZE_REFERENCE = "STANDARDIZE_REFERENCE"

    REFRAME_PROPOSITION = "REFRAME_PROPOSITION"
    ADD_SCOPE_OR_QUALIFICATION = "ADD_SCOPE_OR_QUALIFICATION"
    BALANCE_REPRESENTATION = "BALANCE_REPRESENTATION"

    PRESERVE_AMBIGUITY = "PRESERVE_AMBIGUITY"

    ABSTAIN = "ABSTAIN"


class InstanceAction(StringEnum):
    """
    Sentence- or instance-level action aggregated from span-level actions.
    """

    KEEP = "KEEP"
    EDIT = "EDIT"
    SPAN_LEVEL_EDIT = "SPAN_LEVEL_EDIT"
    ABSTAIN = "ABSTAIN"


class EditScope(StringEnum):
    """Scope at which an intervention is applied."""

    NONE = "NONE"
    SPAN = "SPAN"
    MULTI_SPAN = "MULTI_SPAN"
    SENTENCE = "SENTENCE"
    DOCUMENT = "DOCUMENT"


class ProtectedFactType(StringEnum):
    """Information that a rewrite is not allowed to alter."""

    ENTITY_IDENTITY = "ENTITY_IDENTITY"
    SELF_IDENTIFIED_GENDER = "SELF_IDENTIFIED_GENDER"
    KINSHIP_RELATION = "KINSHIP_RELATION"
    MEDICAL_FACT = "MEDICAL_FACT"
    DEMOGRAPHIC_VARIABLE = "DEMOGRAPHIC_VARIABLE"
    HISTORICAL_STATUS = "HISTORICAL_STATUS"
    NAMED_ENTITY = "NAMED_ENTITY"
    NUMBER_AND_QUANTITY = "NUMBER_AND_QUANTITY"
    TIME_AND_LOCATION = "TIME_AND_LOCATION"
    NEGATION = "NEGATION"
    MODALITY = "MODALITY"
    CAUSALITY = "CAUSALITY"
    SPEAKER_STANCE = "SPEAKER_STANCE"
    ATTRIBUTION = "ATTRIBUTION"
    QUOTATION_CONTENT = "QUOTATION_CONTENT"
    COREFERENCE = "COREFERENCE"
    OTHER = "OTHER"